CREATE TABLE IF NOT EXISTS customer_staging (
    id                    TEXT,
    year_birth            TEXT,
    education             TEXT,
    marital_status        TEXT,
    income                TEXT,
    kidhome               TEXT,
    teenhome              TEXT,
    dt_customer           TEXT,
    recency               TEXT,
    mnt_wines             TEXT,
    mnt_fruits            TEXT,
    mnt_meat_products     TEXT,
    mnt_fish_products     TEXT,
    mnt_sweet_products    TEXT,
    mnt_gold_prods        TEXT,
    num_deals_purchases   TEXT,
    num_web_purchases     TEXT,
    num_catalog_purchases TEXT,
    num_store_purchases   TEXT,
    num_web_visits_month  TEXT,
    accepted_cmp1         TEXT,
    accepted_cmp2         TEXT,
    accepted_cmp3         TEXT,
    accepted_cmp4         TEXT,
    accepted_cmp5         TEXT,
    response              TEXT,
    complain              TEXT,
    z_cost_contact        TEXT,
    z_revenue             TEXT
);  

